### ISSUE TITLE
Sobre o que é seu projeto?

### ISSUE THREAD

**Issue by dvdharrison** [turboflli/IKRPG-estudo#1]
Olá!

Pesquisando IKRPG no GitHub encontrei esse seu projeto, mas não consegui compreender do que se trata. Vi que está bem no início ainda.

**Comment by turboflli** [comment]
ah, olá, desculpa não ter visto sua mensagem antes, é sobre um gerenciador de planilha para mestre, onde coloco os mobs suas vidas, armas, habilidades, salva e carrega em txt, assim pode pausar a aventura
sim ainda estou em desenvolvimento e usando para estudar angular
